### PR TITLE
hi ur codebase is finecet d

### PR DESCRIPTION
**Pull request by cyrus01337**

### CODE REVIEW

**Comment by Depreca1ed** [comment]
You forgot .gitignore

**Review by Hadock-is-ok — APPROVED** [review]
lgtm, push to prod

**Comment by Depreca1ed** [comment]
I am...... Going to look up how to make prs into seperate branches instead of the one they're pring to. Lack of Git knowledge my beloved

**Comment by cyrus01337** [comment]
### I PEAKED

**Comment by Depreca1ed** [comment]
Yk now that I think about it. I definitely fucked up something while merging this PR the way I did because cy does not show up in contributors, assuming that pr author gets added to contrib list when pr is merged

**Comment by Depreca1ed** [comment]
So that's something I guess

**Comment by cyrus01337** [comment]
lol what did you do to the commit history? This PR is naked!

**Comment by Hadock-is-ok** [comment]
pog merge

**Comment by Hadock-is-ok** [comment]
> Yk now that I think about it. I definitely fucked up something while merging this PR the way I did because cy does not show up in contributors, assuming that pr author gets added to contrib list when pr is merged

I think you need to merge 2 prs

**Pull request merged**
